import{a as v,S as E,i}from"./assets/vendor-BK_rxH-O.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const S="51392079-b36bb30a852bc284302a63f16",q="https://pixabay.com/api/",P=15;async function u(s,o=1){const e={key:S,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:P};return(await v.get(q,{params:e})).data}let B=new E(".gallery a",{captionsData:"alt",captionDelay:250});const f=document.querySelector(".gallery"),p=document.querySelector(".loader-wrapper"),h=document.querySelector(".load-more");function m(s){const o=s.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${e.likes}</p>
          <p><b>Views:</b> ${e.views}</p>
          <p><b>Comments:</b> ${e.comments}</p>
          <p><b>Downloads:</b> ${e.downloads}</p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",o),B.refresh()}function $(){f.innerHTML=""}function g(){p.classList.remove("hidden")}function y(){p.classList.add("hidden")}function b(){h.classList.remove("hidden")}function L(){h.classList.add("hidden")}const w=document.querySelector("#search-form"),M=w.elements["search-text"],A=document.querySelector(".load-more");let a=1,l="",d=0;const R=15;w.addEventListener("submit",async s=>{s.preventDefault();const o=M.value.trim();if(!o){i.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}l=o,a=1,$(),L(),g();try{const e=await u(l,a);if(d=e.totalHits,e.hits.length===0){i.info({title:"No Results",message:"❌ Sorry, there are no images matching your search query.",position:"topRight"});return}m(e.hits);const n=document.querySelector(".gallery-item");if(n){const{height:t}=n.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}R>=d?i.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):b()}catch(e){i.error({title:"Error",message:"Failed to fetch images. Try again later.",position:"topRight"}),console.error(e)}finally{y()}});A.addEventListener("click",async()=>{a+=1,g(),L();try{const s=await u(l,a);m(s.hits);const o=document.querySelector(".gallery-item");if(o){const{height:n}=o.getBoundingClientRect();window.scrollBy({top:n*2,behavior:"smooth"})}a*R>=d?i.info({title:"End of Results",message:"You have reached the end of the results.",position:"topRight"}):b()}catch(s){i.error({title:"Error",message:"Could not load more images.",position:"topRight"}),console.error(s)}finally{y()}});
//# sourceMappingURL=index.js.map
