import{a as R,S as v,i as a}from"./assets/vendor-BK_rxH-O.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const P="51392079-b36bb30a852bc284302a63f16",S="https://pixabay.com/api/",q=15;async function u(s,o=1){const e={key:P,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:q};return(await R.get(S,{params:e})).data}let $=new v(".gallery a",{captionsData:"alt",captionDelay:250});const p=document.querySelector(".gallery"),f=document.querySelector(".loader-wrapper"),h=document.querySelector(".load-more");function m(s){const o=s.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${e.likes}</p>
          <p><b>Views:</b> ${e.views}</p>
          <p><b>Comments:</b> ${e.comments}</p>
          <p><b>Downloads:</b> ${e.downloads}</p>
        </div>
      </li>
    `).join("");p.insertAdjacentHTML("beforeend",o),$.refresh()}function B(){p.innerHTML=""}function y(){f.classList.remove("hidden")}function g(){f.classList.add("hidden")}function L(){h.classList.remove("hidden")}function b(){h.classList.add("hidden")}const w=document.querySelector("#search-form"),M=w.elements["search-text"],A=document.querySelector(".load-more");let n=1,c="",d=0;const E=15;w.addEventListener("submit",async s=>{s.preventDefault();const o=M.value.trim();if(!o){a.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}c=o,n=1,B(),b(),y();try{const e=await u(c,n);if(d=e.totalHits,e.hits.length===0){a.info({title:"No Results",message:"❌ Sorry, there are no images matching your search query.",position:"topRight"});return}m(e.hits),E>=d?a.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):L()}catch(e){a.error({title:"Error",message:"Failed to fetch images. Try again later.",position:"topRight"}),console.error(e)}finally{g()}});A.addEventListener("click",async()=>{n+=1,y(),b();try{const s=await u(c,n);m(s.hits);const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),n*E>=d?a.info({title:"End of Results",message:"You have reached the end of the results.",position:"topRight"}):L()}catch(s){a.error({title:"Error",message:"Could not load more images.",position:"topRight"}),console.error(s)}finally{g()}});
//# sourceMappingURL=index.js.map
